version: '3'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./code:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
  app:    
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./code:/var/www
    working_dir: /var/www

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/data/db:/var/lib/my-db
    environment:
      MYSQL_DATABASE: my-db
      MYSQL_ROOT_PASSWORD: root
  
  redis:
    image: redis
    volumes:
      - ./docker/data/redis:/data
